### ISSUE TITLE
Delay between video timings and timestamps

### ISSUE THREAD

**Issue by doganulus** [Eromera/uah_driveset_reader#1]
Hello, 

I have realized that there is some delay between video timings and timestamps for some datasets (didn't check all). What causes such delays? 

Thanks

**Comment by Eromera** [comment]
Hi, the delays are due to the fact that we used a different phone to record the videos than to use the DriveSafe applications, since they cant run in parallel. The driveset_reader tool is meant to synchronize videos and data
